
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { DatabaseWithCustomFunctions } from './customTypes';

const SUPABASE_URL = "https://cdajoyxeulwixtvnrlqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYWpveXhldWx3aXh0dm5ybHFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTIwOTUsImV4cCI6MjA1OTU2ODA5NX0.hSSiYiSHKrSkabYidk5AVOf8hcFdsQ6BVk-4GbhfzKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<DatabaseWithCustomFunctions>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
